# Database Configuration

spring:
r2dbc:
url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
username: sa
password:
pool:
enabled: true
initial-size: 10
max-size: 20

# Enable SQL logging (optional)

logging:
level:
io.r2dbc.h2: DEBUG
org.springframework.data.r2dbc: DEBUG

# Server Configuration

server:
port: 8080

# Logging Configuration

logging:
level:
com.codility.external: DEBUG
org.springframework.web: DEBUG
